name: HIL Test Workflow

on:
  push:
    branches: ["main"]

jobs:
  maker-devops:
    uses: dineshgit411/makers-devops/.github/workflows/hil_checks.yml@main
    with:
      project-yaml: config/project.yml
      user-yaml: config/user.yml
